server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider9002
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.198.128:1111
#        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'